FROM hasura/graphql-engine:v2.36.8
ENV HASURA_GRAPHQL_SERVER_PORT=8080
ENV HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://postgres:postgres@ec2-3-84-220-59.compute-1.amazonaws.com:5432/hasura
ENV PGDATABASE_URL=postgres://postgres:postgres@ec2-3-84-220-59.compute-1.amazonaws.com:5432/faktenforum
ENV HASURA_GRAPHQL_ENABLE_CONSOLE=true
ENV HASURA_GRAPHQL_READ_ONLY_MODE=false
ENV HASURA_GRAPHQL_DEV_MODE=true
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
